config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  root 'welcome#index'

  post 'url' => 'url#create'
  get 'url/new' => 'url#new'
  get 'url/:alias' => 'url#show'

end

app/models/url.rb
class Url < ActiveRecord::Base

	validates :url, :presence => true
	validates_format_of :url, :with => URI::regexp(%w(http https)), :message => 'Invalid URL format. Please use ex. "http://www.google.com"'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/url_controller.rb
class UrlController < ApplicationController

	# fetch by alias and redirect to URL
	def show
		url = Url.where(alias: params[:alias])
		if url.length > 0
			# alias exists in db
			redirect_to url.first.url
		else
			render plain: 'Invalid redirect.'
		end
	end

	def new
	end

	# Takes a valid url and creates a shortened url from it.
	def create

		# ensure url is valid
		new = Url.new(params.require(:shortener).permit(:url, :alias))
		if (!new.valid?(:url))
			render plain: new.errors.messages and return
		end

		# ensure url does not already exist
		url = Url.where(url: params[:shortener][:url])
		if url.length > 0
			render plain: 'URL already shortened. See: ' + url_for(controller: 'url', action: 'create') + '/' + url.first.alias
			return
		end

		# check if user specified custom alias
		if params[:shortener][:alias] && params[:shortener][:alias].length > 0
			# check if alias has been used
			_alias = Url.where(alias: params[:shortener][:alias])
			if _alias.length == 0
				# alias has not been chosen
				new.save
				render plain: 'Success! See it here: ' + url_for(controller: 'url', action: 'create') + '/' +  params[:shortener][:alias]
			else
				render plain: 'Alias already exists :( Try again.'
			end
		else
			# generate random alias: id + 3 char random string
			new.save
			new.update(alias: new.id.to_s + (0...3).map { (65 + rand(26)).chr }.join)
			render plain: 'Here is your shortened URL: ' + url_for(controller: 'url', action: 'create') + '/' + new.alias
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlMinify</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/url/new.html.erb
<%= form_for :shortener, url: url_path do |f| %>
  <p>
    <strong>URL</strong><br>
    <%= f.text_field :url, :placeholder => "ex: 'http://www.google.com'", :style => "width: 200px;" %>
  </p>

  <p>
    <strong>Custom Alias</strong><br>
    (Optional; URL will be: http://url-min.herokuapp.com/url/[alias] or we'll generate it for you.)<br>
    <%= f.text_field :alias, :placeholder => "ex: 'goog'", :style => "width: 200px;" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>URL Minify</h1>
<h2>Simple project demonstrating URL rerouting and/or shortening.</h2>
<h3>Examples</h3>
<ul>
  <li>http://www.google.com - <a href="http://url-min.herokuapp.com/url/g">http://url-min.herokuapp.com/url/g</a></li>
  <li>http://www.facebook.com - <a href="http://url-min.herokuapp.com/url/fb">http://url-min.herokuapp.com/url/fb</a></li>
  <li>http://news.ycombinator.com - <a href="http://url-min.herokuapp.com/url/hn">http://url-min.herokuapp.com/url/hn</a></li>
</ul>

<h4><a href="url/new">Get started!</a></h4>